config/routes.rb
Rails.application.routes.draw do
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  root 'home#index'
  resources :contacts
  resources :failed_contacts
  resources :uploaded_files do
    post 'process_file', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  self.per_page = 10
  validates :name, :date_of_birth, :phone, :address, :credit_card, :franchise, :email, :card_last4, :uploadedfile_id, presence: true
  validate :name_format, :date_format, :phone_format, :card_format, :email_format, on: :create
  validates_uniqueness_of :email, scope: :user_id
  def date_format
    validation = DateFormatValidationService.new(self.date_of_birth).execute
    errors.add(:date_of_birth, 'Invalid date format') unless validation
  end

  def name_format
    validation = self.name.match?(/\A[a-zA-Z- ]*\z/) ? true : false
    errors.add(:name, 'Invalid name format') unless validation
  end

  def card_format
    CardValidationService.new(self.credit_card).execute
  end

  def email_format
    validation =  self.email.match?(/^[\+A-Z0-9\._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i) ? true : false
    errors.add(:email, 'Invalid email format') unless validation
  end

  def phone_format
    validation = PhoneFormatValidationService.new(self.phone).execute
    errors.add(:phone, 'Invalid phone format') unless validation
  end

end

app/models/credit_card_franchise.rb
class CreditCardFranchise < ApplicationRecord
end

app/models/credit_card_franchise_detail.rb
class CreditCardFranchiseDetail < ApplicationRecord
end

app/models/failed_contact.rb
class FailedContact < ApplicationRecord
  self.per_page = 10
  def file_name
    file = UploadedFile.find(self.uploadedfile_id)
    "#{file.file}"
  end
end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
  has_one_attached :main_file
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActionController::ParameterMissing do |e|
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = Contact.where("user_id = #{current_user.id}").paginate(:page => params[:page], :per_page => 30)
  end

end

app/controllers/failed_contacts_controller.rb
class FailedContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = FailedContact.where(:user_id => current_user.id).paginate(:page => params[:page]).order('id DESC')
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  require 'csv'
  require "#{Rails.root}/lib/contact_column.rb"
  before_action :authenticate_user!
  VALID_COLUMNS = ["name", "date_of_birth", "phone", "address", "credit_card", "email", "lastname"]

  def index
    @uploaded_files = UploadedFile.where(:user_id => current_user.id).paginate(:page => params[:page]).order('id DESC')
  end

  def new
    @uploaded_file = UploadedFile.new
  end

  def show
    uploaded_file
  end

  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)
    @uploaded_file.state = 'ON HOLD'
    @uploaded_file.user_id = current_user.id
    if @uploaded_file.save
      uploaded_file(@uploaded_file.id)
    end
  end

  def process_file
    columns_order = []
    file_columns = []
    params[:uploaded_files]["contact_columns"].each do |key, value|
      columns_order.push(value.gsub(" ", ""))
    end
    params[:uploaded_files]["file_colums"].each do |key, value|
      file_columns.push(value.gsub(" ", ""))
    end
    file_id = params[:file_id]
    columns_order.uniq!
    if columns_order.count != file_columns.count
      uploaded_file(file_id)
      flash[:notice] = 'You made a mistake while selecting the columns. Try again.'
      render 'show'
    end
    ProcessFileWorker.perform_async(file_id, columns_order, current_user.id)
  end

  private
    def uploaded_file_params
      params.require(:uploaded_file).permit(:title, :state, :user_id, :file, :main_file)
    end

    def uploaded_file(uploaded_file_id)
      @file_id = uploaded_file_id
      @columns_collection = []
      (Contact.column_names).each do |column|
        item = ContactColumn.new(column,column)
        @columns_collection.push(item) if VALID_COLUMNS.include? column  
      end
      @file = UploadedFilePreProcessService.new(@file_id).execute
      if @file.count != @columns_collection.count
        flash[:notice] = 'The number of columns is not valid.'
        redirect_to new_uploaded_file_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ContactImporter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= contacts_path %>">Contacts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= failed_contacts_path %>">FailedContacts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= uploaded_files_path %>">FilesLog</a>
        </li>
      </ul>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link btn-danger" data-method="delete" href="<%= destroy_user_session_path %>">Sign out </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<%= link_to "Upload Contacts", new_uploaded_file_path, class: "btn btn-primary" %>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date of Birth</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Email</th>
      <th scope="col">Card_Last4</th>
      <th scope="col">Franchise</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.date_of_birth.to_date.strftime("%Y %B %-d") %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.email %></td>
        <td><%= contact.card_last4 %></td>
        <td><%= contact.franchise %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/failed_contacts/index.html.erb
<h1>Failed Contacts</h1>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">File Name</th>
      <th scope="col">File Line</th>
      <th scope="col">Error Message</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.file_name %></td>
        <td><%= contact.file_line %></td>
        <td><%= contact.error_message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactProvider</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if user_signed_in? %>
      <%= render "navbar" %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploaded_files/_form.html.erb
<div class="alert alert-danger ml-1" role="alert">
  <p id="notice" class = "mb-2"><%= notice %></p>
</div>
<%= form_with model: @uploaded_file, local: true do |f| %>
  <%= f.file_field :main_file, class: "form-control-file" %>
  <%= f.submit 'Upload File', class: "btn btn-success mt-1" %>
<% end %>

app/views/uploaded_files/_uploaded_file.html.erb
<h5 class = "mt-2">File has been uploaded. Check the columns to match them with their corresponding one before processing the file</h5>
  <%= form_with url: process_file_uploaded_file_path(id: @file_id), local:true do |f| %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">File Column</th>
        <th scope="col">Contact Info Column</th>
      </tr>
    </thead>
    <tbody>
      <% @file.each_with_index do |header, i| %>
        <%= f.hidden_field :file_id, value: @file_id %>
        <tr>
          <td><%= f.text_field :file_column, name: "[uploaded_files][file_colums][file_col#{i}]", id: "file-col#{i}", value: header, class: "form-control" %></td>
          <td><%= f.select :contact_column, options_from_collection_for_select(@columns_collection, 'id', 'value'), {}, name: "[uploaded_files][contact_columns][contact_col#{i}]", class: "form-control" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center"><%= f.submit 'Process', class: "btn btn-success" %></div>
<% end %>

app/views/uploaded_files/create.html.erb
<%= render "uploaded_file" %>

app/views/uploaded_files/index.html.erb
<h1>UploadedFiles</h1>
<%= will_paginate @uploaded_files, renderer: BootstrapPagination::Rails %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">File Name</th>
      <th scope="col">State</th>
    </tr>
  </thead>
  <tbody>
    <% @uploaded_files.each do |file| %>
      <tr>
        <td><%= file.id %></td>
        <td><%= file.file.to_s.gsub("/uploads/", "") %></td>
        <% case file.state %>
          <% when 'ON HOLD' %>
            <td class = "bg-secondary">
          <% when 'PROCESSING' %>
            <td class = "bg-info">
          <% when 'FINISHED' %>
            <td class = "bg-success">
          <% when 'FAILED' %>
            <td class = "bg-danger">
        <% end %>
        <%= file.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/uploaded_files/new.html.erb
<%= render "form" %>

app/views/uploaded_files/process_file.html.erb
<h5 class = "mt-2">Your file is been processed. Check the status in the <%= link_to 'Files Logs', uploaded_files_path() %></h5>

app/views/uploaded_files/show.html.erb
<div class="alert alert-danger ml-1" role="alert">
  <p id="notice" class = "mb-2"><%= notice %></p>
</div>
<%= render "uploaded_file" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-info mt-1" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-info mt-1" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-info mt-1" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-info mt-1" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-info mt-1" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-info mt-1" %><br />
  <% end %>
<% end %>